export const FETCH_ASSIGNMENTS = 'FETCH_ASSIGNMENTS';
export const FETCH_ASSIGNMENTS_SUCCESS = 'FETCH_ASSIGNMENTS_SUCCESS';
export const FETCH_ASSIGNMENTS_ERROR = 'FETCH_ASSIGNMENTS_ERROR';

export const FETCH_ASSIGNMENT_SUBMISSIONS = 'FETCH_ASSIGNMENT_SUBMISSIONS';
export const FETCH_ASSIGNMENT_SUBMISSIONS_SUCCESS = 'FETCH_ASSIGNMENT_SUBMISSIONS_SUCCESS';
export const FETCH_ASSIGNMENT_SUBMISSIONS_ERROR = 'FETCH_ASSIGNMENT_SUBMISSIONS_ERROR';

export const NORMALIZED_DATA_REPLACE = 'NORMALIZED_DATA_REPLACE';
export const NORMALIZED_DATA_MERGE = 'NORMALIZED_DATA_MERGE';
